language: python

python:
  - "3.7"
before_install:
  - pip install codecov
  - pip install pytest 'pytest-cov==2.5.0'
install:
  - pip install -q coverage
  - pip install -r requirements.txt
  - pip install .
script: ./build_and_test.sh
after_success:
  - codecov
branches:
  only:
    - master